# Generated by Django 2.1.1 on 2018-09-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180906_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Album_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
